name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag flavienperier/dns:$GITHUB_SHA
    - name: Push the tagged Docker image
      run: docker push flavienperier/dns:$GITHUB_SHA

  build-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag flavienperier/dns:latest
    - name: Push the latest Docker image
      run: docker push flavienperier/dns:latest
